# Generated by Django 3.1.2 on 2020-10-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dueDate',
        ),
    ]
